//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandingPageExample.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.User_Activity = new HashSet<User_Activity>();
        }
    
        public int Id { get; set; }
        [Display(Name = "User Name")]
        [Required]
        [MinLength(2)][MaxLength(20)]
        [RegularExpression("^[a-z0-9]*$", ErrorMessage = "Only lowercase and Numbers allowed.")]
        public string UserName { get; set; }
        [Required]
        [MinLength(6)][MaxLength(20)]
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Activity> User_Activity { get; set; }
    }
}
